### ISSUE TITLE
2.1 Cross domain requests in oldIE

### ISSUE THREAD

**Issue by KrijnHoetmer** [BerendPronk/minor-bt#4]
> Note: The live version of this demo will not properly work in Internet Explorer 7, since it denies access to the API via HTTPS. If you clone this repo, or copy the contents of javascript-fetch.html to view the demo locally, it'll work just fine.

If you ever run into this problem again, check out [XDomainRequest](https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest). And let's hope you never do :)

**Comment by BerendPronk** [comment]
:+1:
